### ISSUE TITLE
问题：canvas边框绘制不全、内容文本y轴定位错误

### ISSUE THREAD

**Issue by yaodebian** [Mying666/myEcTooltip#2]
本人在使用楼主代码时发现一些小问题(楼主的demo确实没问题，但当内容文本比较多时就会产生问题)，如图（图片已马赛克处理）：
![7A11582C55647394A7A13AD5DDF97DAB](https://user-images.githubusercontent.com/35584587/54581040-ca600500-4a45-11e9-9bab-ddb3c7e70698.jpg)

之后浏览了楼主的代码，发现以下这块有点问题：
<img width="266" alt="2" src="https://user-images.githubusercontent.com/35584587/54581146-5d00a400-4a46-11e9-9f09-62fe65f2d13d.png">

第一行代码的问题是没有针对top字段进行处理，第二行是传参的第二个参数计算错误，改成下面就好了：
```
me.config.top ? me.textContainer.y = L2End[1] - c.text.height / 2 : me.textContainer.y = L2End[1] - c.L1.long * Math.sin(Math.PI / 4)

me.textBorder(c.text.width, c.text.height / 2 + c.L1.long * Math.sin(Math.PI / 4))
```

**Comment by zss1004504439** [comment]
不行 文本还是不能自适应

**Comment by yaodebian** [comment]
> 不行 文本还是不能自适应

他这个就是不能自适应文本的，宽度是需要自己设死的，如果文本要换行则需要自己设置换行符
这里指出的是代码上原来就是有问题的，边框和y轴定位是有问题的

**Comment by chengpeng12** [comment]
vue可以使用这个吗？js依赖是不是export暴露的，不知道在vue里使用import能不能直接使用

**Comment by Crystalichun** [comment]
感谢大神！！！解决了我的问题！！
